
#config matter power spectrum
z: 0

m_min: 1
N_m: 64 #power of 2

M_min: 1e6
M_max: 1e16
N_M: 64 #power of 2


k_min: 1e-1
k_max: 1e4
N_k: 64 #power of 2

# Delta_vir: 340 #See figure 1 in eke et al. for some value of Omega_m
# Delta_vir is 340 times the mean matter density so 340m

massdef: "200c" # !! SHOULD LEAVE THIS BY DEFAULT ON 200m

# factor multiplicator for concentration of clumps
Q: 1

# Gas profile
theta_ej: 6
delta: 8
gamma: 3
mu: 1
logM_c: 13.2
logM_gaslimit: 10

# Stellar profile
r_h: 0.015 # radius of galaxies times r200

# SHMR
S: 1.8 #factor before stellar fraction # THIS DOESNT WORK YET POWER GETS TAKEN AWAY AT LARGE SCALES

# config convergence power spectrum
z_min: 0
z_max: 2
N_z: 11    #amount of redshift points to sample from
l_min: 1e1
l_max: 1e6
N_l: 256  #Number of points along l used for interpolation

# xi correlation
theta_min: 1 # minimum angular scale for xi+ (in arcsecs)
theta_max: 1e3 # maximum angular scale for xi+ (in arcsecs)
N_theta: 10 # number of theta bins

# Cosmology parameters 
cosmo_params:
  flat: true
  H0: 70
  Om0: 0.2793
  Ob0: 0.0463
  sigma8: 0.7207
  ns: 0.972

# halo mass function parameters
M0: 2e9
alpha: 0

#clump mass function parameters
m0: 2e9
beta: 0

#data storage
Pm_dir: '/home/milan/Desktop/thesis/code/data/matter_power_spectra/regular'
Pk_dir: '/home/milan/Desktop/thesis/code/data/convergence_power_spectra/regular'